x-service: &service-defaults
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

x-healthcheck: &healthcheck
  interval: 15s
  timeout: 5s
  retries: 5
  start_period: 15s

services:
  # ── Infrastructure ───────────────────────────────────────────────────

  postgres:
    <<: *service-defaults
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-manifest}
      POSTGRES_USER: ${POSTGRES_USER:-manifest}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-manifest}"]
      <<: *healthcheck

  redis:
    <<: *service-defaults
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD:-manifest}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-manifest}", "ping"]
      <<: *healthcheck

  opensearch:
    <<: *service-defaults
    image: opensearchproject/opensearch:2.17.1
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  minio:
    <<: *service-defaults
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-manifest}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}
      MINIO_API_CORS_ALLOW_ORIGIN: ${MINIO_API_CORS_ALLOW_ORIGIN:-http://localhost:3000}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/minio/health/live || exit 1"]
      <<: *healthcheck

  redpanda:
    <<: *service-defaults
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=redpanda:8082

  # ── Backend Services ─────────────────────────────────────────────────

  notification-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/notification-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4010"
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4010/health || exit 1"]
      <<: *healthcheck

  identity-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/identity-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4005"
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER:-manifest}:${POSTGRES_PASSWORD:?}@postgres:5432/${POSTGRES_DB:-manifest}"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4005/health || exit 1"]
      <<: *healthcheck

  profile-project-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/profile-project-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4001"
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER:-manifest}:${POSTGRES_PASSWORD:?}@postgres:5432/${POSTGRES_DB:-manifest}"
      NOTIFICATION_SERVICE_URL: "http://notification-service:4010"
    depends_on:
      postgres:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4001/health || exit 1"]
      <<: *healthcheck

  search-indexer-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/search-indexer-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4003"
      NODE_ENV: production
      OPENSEARCH_URL: "http://opensearch:9200"
      OPENSEARCH_INDEX: "competitions_v1"
    depends_on:
      opensearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4003/health || exit 1"]
      <<: *healthcheck

  competition-directory-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/competition-directory-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4002"
      NODE_ENV: production
      SEARCH_INDEXER_URL: "http://search-indexer-service:4003"
      NOTIFICATION_SERVICE_URL: "http://notification-service:4010"
    depends_on:
      search-indexer-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4002/health || exit 1"]
      <<: *healthcheck

  script-storage-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/script-storage-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4011"
      NODE_ENV: production
      STORAGE_BUCKET: "scripts"
      STORAGE_UPLOAD_BASE_URL: ${STORAGE_UPLOAD_BASE_URL:-http://localhost:9000}
      STORAGE_PUBLIC_BASE_URL: ${STORAGE_PUBLIC_BASE_URL:-http://minio:9000}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT:-http://minio:9000}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION:-us-east-1}
      STORAGE_S3_ACCESS_KEY: ${MINIO_ROOT_USER:-manifest}
      STORAGE_S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}
      STORAGE_S3_FORCE_PATH_STYLE: ${STORAGE_S3_FORCE_PATH_STYLE:-true}
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4011/health || exit 1"]
      <<: *healthcheck

  submission-tracking-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/submission-tracking-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4004"
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4004/health || exit 1"]
      <<: *healthcheck

  feedback-exchange-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/feedback-exchange-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4006"
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER:-manifest}:${POSTGRES_PASSWORD:?}@postgres:5432/${POSTGRES_DB:-manifest}"
      NOTIFICATION_SERVICE_URL: "http://notification-service:4010"
    depends_on:
      postgres:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4006/health || exit 1"]
      <<: *healthcheck

  ranking-service:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/ranking-service:${IMAGE_TAG:-latest}
    environment:
      PORT: "4007"
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER:-manifest}:${POSTGRES_PASSWORD:?}@postgres:5432/${POSTGRES_DB:-manifest}"
      NOTIFICATION_SERVICE_URL: "http://notification-service:4010"
      SUBMISSION_TRACKING_SERVICE_URL: "http://submission-tracking-service:4004"
      COMPETITION_DIRECTORY_SERVICE_URL: "http://competition-directory-service:4002"
      PROFILE_SERVICE_URL: "http://profile-project-service:4001"
    depends_on:
      postgres:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      submission-tracking-service:
        condition: service_healthy
      competition-directory-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4007/health || exit 1"]
      <<: *healthcheck

  api-gateway:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/api-gateway:${IMAGE_TAG:-latest}
    ports:
      - "${API_PORT:-4000}:4000"
    environment:
      PORT: "4000"
      NODE_ENV: production
      IDENTITY_SERVICE_URL: "http://identity-service:4005"
      PROFILE_SERVICE_URL: "http://profile-project-service:4001"
      COMPETITION_DIRECTORY_SERVICE_URL: "http://competition-directory-service:4002"
      SUBMISSION_TRACKING_SERVICE_URL: "http://submission-tracking-service:4004"
      SCRIPT_STORAGE_SERVICE_URL: "http://script-storage-service:4011"
      FEEDBACK_EXCHANGE_SERVICE_URL: "http://feedback-exchange-service:4006"
      RANKING_SERVICE_URL: "http://ranking-service:4007"
    depends_on:
      identity-service:
        condition: service_healthy
      profile-project-service:
        condition: service_healthy
      competition-directory-service:
        condition: service_healthy
      submission-tracking-service:
        condition: service_healthy
      feedback-exchange-service:
        condition: service_healthy
      ranking-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/health/live || exit 1"]
      <<: *healthcheck

  # ── Frontend ─────────────────────────────────────────────────────────

  writer-web:
    <<: *service-defaults
    image: ghcr.io/full-chaos/script-manifest/writer-web:${IMAGE_TAG:-latest}
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      SCRIPT_STORAGE_SERVICE_URL: "http://script-storage-service:4011"
      API_GATEWAY_URL: "http://api-gateway:4000"
      SCRIPT_UPLOAD_INTERNAL_BASE_URL: ${SCRIPT_UPLOAD_INTERNAL_BASE_URL:-http://minio:9000}
    depends_on:
      api-gateway:
        condition: service_healthy
      script-storage-service:
        condition: service_healthy

volumes:
  postgres_data:
  opensearch_data:
  minio_data:
