-- Migration 019: onboarding progress tracking

CREATE TABLE IF NOT EXISTS onboarding_progress (
  user_id TEXT PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
  profile_completed BOOLEAN NOT NULL DEFAULT FALSE,
  project_added BOOLEAN NOT NULL DEFAULT FALSE,
  first_script_uploaded BOOLEAN NOT NULL DEFAULT FALSE,
  competitions_visited BOOLEAN NOT NULL DEFAULT FALSE,
  coverage_visited BOOLEAN NOT NULL DEFAULT FALSE,
  submission_recorded BOOLEAN NOT NULL DEFAULT FALSE,
  placement_recorded BOOLEAN NOT NULL DEFAULT FALSE,
  export_used BOOLEAN NOT NULL DEFAULT FALSE,
  share_used BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE onboarding_progress
  ADD COLUMN IF NOT EXISTS project_added BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS submission_recorded BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS placement_recorded BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS export_used BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS share_used BOOLEAN NOT NULL DEFAULT FALSE;
